name: cloudnet
description: A App to administarte cloudnet resources like permissions, servers and more
repository: https://github.com/TheMeinerLP/CloudNet-App
homepage: https://cloudnetservice.eu/
issue_tracker: https://github.com/TheMeinerLP/CloudNet-App/issues


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # add this
    sdk: flutter
  path_provider: ^2.0.8
  cupertino_icons: ^1.0.4
  # architecture
  async_redux: ^13.2.2
  dio: ^4.0.4
  dio_cache_interceptor: ^3.2.2
  freezed_annotation: ^1.1.0
  localstorage: ^4.0.0+1
  go_router: ^3.0.1
  form_validator: ^1.0.1
  jwt_decoder: ^2.0.1
  fluttericon: ^2.0.0
  easy_rich_text: ^1.0.3
  web_socket_channel: ^2.1.0
  connectivity_plus: ^2.2.0
  search_choices: ^2.0.17
  network_info_plus: ^2.1.2
  package_info_plus: ^1.3.0


dev_dependencies:
  build_runner: any
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  flutter_lints: 1.0.4
  fast_i18n: ^5.9.0
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - '.github/assets/img/Logo.png'
    - '.github/assets/img/Logo.png'
    - '.github/assets/img/Discord-Icon.png'
    - '.github/assets/img/TeamDiscord-Icon.png'