name: cloudnet_v3_flutter
description: The new webinterface and app for cloudnet

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # architecture
  async_redux: ^12.0.0
  dio: ^4.0.0
  dio_cache_interceptor: ^3.0.1
  freezed_annotation: ^0.14.3
  localstorage: ^4.0.0+1
  go_router: ^2.2.4
  i18n_extension: ^4.1.3


dev_dependencies:
  build_runner: any
  envify_generator: ^2.0.2
  freezed: ^0.14.5
  json_serializable: ^5.0.0
  lint: ^1.7.2

flutter:
  uses-material-design: true
