name: CloudNet
description: The new webinterface and app for cloudnet

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  # architecture
  async_redux: ^13.2.0
  dio: ^4.0.4
  dio_cache_interceptor: ^3.0.3
  freezed_annotation: ^1.1.0
  localstorage: ^4.0.0+1
  go_router: ^2.5.5
  i18n_extension: ^4.1.3
  form_validator: ^1.0.1


dev_dependencies:
  build_runner: any
  envify_generator: ^2.0.2
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  flutter_lints: 1.0.4

flutter:
  uses-material-design: true
